device: gpu               # Computation device (cpu/gpu)
solutions: 200            # Number of parallel solutions
total_iter: 10           # Total optimization iterations
parallel_task: 256       # Number of parallel MC tasks
converge_depth: 10       # Convergence criterion
weight:                  # Shell weights for fitness
  - 1.0
structure: POSCAR  # Input structure file
target_sro: sro
cut_iter: 9
cutoff:
- 5
mc_num_lattice_per_batch: 3
mc_batch_num: 1
mc_num_tasks: 256
mc_search_depth: 10
mc_fitness_threshold: 1
mc_initial_temperature: 0.01
mc_cooling_rate: 0.9
mc_annealing_steps: 10

